### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by rahji** [leomcelroy/gram#2]
Is it possible to provide build instructions in the readme? I am trying to add a feature (auto-update the view) but I'm having trouble figuring out how to build from source afterwards.

**Comment by leomcelroy** [comment]
Yes. This repo really needs a refresh. I'll take a pass this week or next. Glad to see you're working on contributions.

**Comment by rahji** [comment]
Yes, I'd like to take a stab at adding an auto-update-view option and also the ability to use different fonts. My students are working with Gram for a couple of weeks and I'd like to keep using it in future - such a great tool.

**Comment by leomcelroy** [comment]
This issue prompted me to descend into a rabbit hole which resulted in rewriting everything (including my own text editor from scratch). Unfortunately this rewrite isn't quite stable yet so I decided to do the 5 hours of coding I originally planned to do which addresses this for the current stable release. 

Now you just need to navigate to the repo and run a dev server. I often use [live-server](https://www.npmjs.com/package/live-server) and have it installed globally.
