### ISSUE TITLE
Download SVG is broken

### ISSUE THREAD

**Issue by rahji** [leomcelroy/gram#4]
It seems like the recent changes have made SVG download not work. Here's the error I get in the console when I try to do it:

```
download.js:17 Uncaught TypeError: oneTurtle.move is not a function
    at downloadSVG (download.js:17:30)
    at HTMLButtonElement.<anonymous> (addEvents.js:181:5)
downloadSVG @ download.js:17
(anonymous) @ addEvents.js:181
```
I've tried with a script as simple as the following:

```
rectangle 4 4
```

**Comment by rahji** [comment]
I confirmed that it works okay with the previous version tagged 0.0.2

**Comment by leomcelroy** [comment]
Thanks for noting! I'll check this out.

**Comment by leomcelroy** [comment]
Should be fixed now!
